--- #YAML:1.0
name:               PNI-Core
version:            0.05
abstract:           Perl Node Interface core bundle
author:
    - G. Casati <fibo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PNI:                 0.20
    PNI::Node::Perlvar:  0.03
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
